# Generated by Django 5.2.14 on 2026-05-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travello", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="description",
            field=models.TextField(default="sample"),
        ),
        migrations.AddField(
            model_name="destination",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
